### ISSUE TITLE
Plugin system for providers

### ISSUE THREAD

**Issue by extremeshok** [maelgangloff/domain-watchdog#47]
Currently to add a new provider one would need to edit approx 6-8 core files, besides adding the provider file.

It would be beneficial if we could add providers using a single file, and invoke/override a provider class all in the single file.

**Comment by maelgangloff** [comment]
To add a connector you need to:
- For the backend, create a class in the namespace `App\Config\Provider` that extends from [`AbstractProvider`](https://github.com/maelgangloff/domain-watchdog/blob/master/src/Config/Provider/AbstractProvider.php) and add the class in the [`ConnectorProvider`](https://github.com/maelgangloff/domain-watchdog/blob/master/src/Config/ConnectorProvider.php) enumerator.
- For the frontend, modify the form so that it displays the fields specific to this connector.

Saying that you have to modify 6-8 core files seems somewhat exaggerated to me. I should point out that I added an abstraction to make adding a provider as simple as possible.

Can you tell me more about this request? I'm curious how to make this even easier ;)
Some provider APIs are really very different from each other.

**Comment by vinceh121** [comment]
I've taken a quick glance at how this would be implemented, but it seems the entire tech stack is against this. Both PHP and Symfony don't favor SPIs, despite Symfony's dependency injection.

Not only this, but providers all have different needs that will inherently need a change in DW's behaviour in order to implement them. e.g. I'm working on implementing Namecheap, which requires to provide the current outgoing IP, as such a new envvar has to be supported, which requires modifying Symfony's dependency injection config file.

On the "ecosystem" aspect, I think a plugin system is detrimental because DW is still a young project (and so are the technologies it relies on) and the APIs will frequently change, so plugins will frequently be left outdated if their version control isn't in sync with DW, while having all connectors directly implemented into DW will force them to stay updated on refactors.
